site_name: Tricore GNU Toolchain
repo_url: https://github.com/NoMore201/tricore-gcc-toolchain
repo_name: tricore-gcc-toolchain
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

nav:
  - Home: index.md
  - Build: building.md
  - Debug with QEMU+GDB: qemu-debug.md
  - Changelog: changelog.md
