#!/usr/bin/env bash

###############################################################
#
# This script builds QEMU cross compile dependencies and
# installs them into the provided prefix. Currently only
# Glib2 is required.
#
# Usage: ./build-mingw-deps /opt/install-prefix
#
###############################################################

set -euo pipefail

GLIB_VERSION=2.83.0
GLIB_TARBALL="glib-$GLIB_VERSION.tar.xz"
GLIB_SRC_URL="https://download.gnome.org/sources/glib/2.83/glib-$GLIB_VERSION.tar.xz"

ARCH=x86_64-w64-mingw32

if [ $# -ne 1 ]; then
    echo "Script require install prefix path as parameters"
    exit 1
fi

INSTALL_PREFIX=$1

if [ ! -f $GLIB_TARBALL ]; then
    curl -L --insecure --remote-name-all  $GLIB_SRC_URL
fi
tar xJf $GLIB_TARBALL
cd "glib-$GLIB_VERSION"

cat > $ARCH.txt <<HereDoc
[binaries]
c = '$ARCH-gcc'
cpp = '$ARCH-g++'
ar = '$ARCH-ar'
windres = '$ARCH-windres'
strip = '$ARCH-strip'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
HereDoc

meson setup --cross-file $ARCH.txt build-mingw --prefix="$INSTALL_PREFIX" --buildtype=release \
    --default-library=static \
    -Dintrospection=disabled \
    -Ddtrace=disabled \
    -Dsystemtap=disabled \
    -Dsysprof=disabled \
    -Dglib_debug=disabled
cd build-mingw
meson compile
meson install