#!/bin/sh

set -e

if [ ! -f /etc/lsb_release ] && [ ! -f /etc/debian_version ]
then
    echo "Script is meant to install packages on Debian/Ubuntu based distributions"
    echo "Please install dependencies manually on other distributions"
    exit 1
fi

apt-get update
apt-get -y install build-essential texinfo \
    flex bison libmpfr-dev libgmp-dev libmpc-dev zip libdebuginfod-dev \
    gcc-mingw-w64 g++-mingw-w64 mingw-w64-tools \
    git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build \
    python3-dev python3-pip

pip install meson
