#!/bin/sh

set -e

fetch_cmd="curl -LO"
gmp='gmp-6.1.0.tar.bz2'
mpfr='mpfr-3.1.6.tar.bz2'
mpc='mpc-1.0.3.tar.gz'
base_url='http://gcc.gnu.org/pub/gcc/infrastructure/'

gmp_folder=${gmp%.tar.*}
mpfr_folder=${mpfr%.tar.*}
mpc_folder=${mpc%.tar.*}

if [ -z "$1" ]; then
    host_flag=""
else
    host_flag="--host=$1"
fi

# Download dependencies GMP, MPFR, MPC
$fetch_cmd "${base_url}${gmp}"
$fetch_cmd "${base_url}${mpfr}"
$fetch_cmd "${base_url}${mpc}"

tar -xf "${gmp}"
tar -xf "${mpfr}"
tar -xf "${mpc}"

start_dir=$(pwd)

export CFLAGS="-O2"
export CXXFLAGS="-O2"

if [ -d build-gmp ]; then
    rm -rf build-gmp
fi
mkdir build-gmp && cd build-gmp
"${start_dir}/${gmp_folder}/configure" \
    --prefix=/deps \
    $host_flag \
    --disable-assembly \
    --enable-static \
    --disable-shared
make && make install

cd "${start_dir}"

if [ -d build-mpfr ]; then
    rm -rf build-mpfr
fi
mkdir build-mpfr && cd build-mpfr
"${start_dir}/${mpfr_folder}/configure" \
    --prefix=/deps \
    $host_flag \
    --with-gmp-include=/deps/include \
    --with-gmp-lib=/deps/lib \
    --enable-static \
    --disable-shared
make && make install

cd "${start_dir}"

if [ -d build-mpc ]; then
    rm -rf build-mpc
fi
mkdir build-mpc && cd build-mpc
"${start_dir}/${mpc_folder}/configure" \
    --prefix=/deps \
    $host_flag \
    --with-gmp-include=/deps/include \
    --with-gmp-lib=/deps/lib \
    --with-mpfr-include=/deps/include \
    --with-mpfr-lib=/deps/lib \
    --enable-static \
    --disable-shared
make && make install