name: Build

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  linux-build:
    name: Toolchain build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential build-essential texinfo \
            flex bison libmpfr-dev libgmp-dev libmpc-dev zip libdebuginfod-dev \
            gcc-mingw-w64 g++-mingw-w64

      - name: Build
        run: |
          mkdir build
          cd build
          export CFLAGS="-O2"
          export CXXFLAGS="-O2"
          export LDFLAGS="-static -s"
          ../configure --prefix /opt/gcc
          make -j$(nproc)

      - name: Package
        run: |
          cd /opt/gcc/linux
          zip -r9 ../linux.zip .
          cd /opt/gcc/win32
          zip -r9 ../win32.zip .
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: tricore-gcc-artifacts
          path: /opt/gcc/*.zip

