name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Toolchain build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential build-essential gcc-mingw-w64 g++-mingw-w64 texinfo flex bison libmpfr-dev libgmp-dev libmpc-dev zip libdebuginfod-dev zlib

      - name: Build Linux
        run: |
          mkdir build-linux
          cd build-linux
          ../configure --prefix /opt/linux
          make -j$(nproc)

      - name: Build Win32
        run: |
          mkdir build-win32
          cd build-win32
          ../configure --prefix=/opt/win32 --with-host=x86_64-w64-mingw32
          make -j$(nproc)

      - name: Package
        run: |
          cd /opt/linux
          zip -r9 ../linux.zip .
          cd /opt/win32
          zip -r9X ../win32.zip .
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: tricore-gcc-artifacts
          path: /opt/**/*.zip
