name: Build

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Toolchain build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo ./install-deps

      - name: Build
        run: ./build-toolchain

      - name: Package
        run: |
          cd ./INSTALL
          zip -r9 ../linux.zip .
          cd ../INSTALL-WIN
          zip -r9X ../win32.zip .
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: tricore-gcc-artifacts
          path: ./*.zip
