name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Publish Release artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: ${{ github.event.release.target_commitish }}
          workflow_conclusion: success
          skip_unpack: false

      - name: Prepare linux package
        run: |
          mkdir linux-bundle && cd linux-bundle
          unzip ../tricore-gcc-artifacts/gcc-linux.zip
          unzip ../tricore-qemu-artifacts/qemu-linux.zip
          zip -r9X tricore-gcc-${{ github.ref_name }}-linux.zip ./*

      - name: Prepare windows package
        run: |
          mkdir win32-bundle && cd win32-bundle
          unzip ../tricore-gcc-artifacts/gcc-win32.zip
          unzip ../tricore-qemu-artifacts/qemu-win32.zip
          zip -r9X tricore-gcc-${{ github.ref_name }}-win32.zip ./*

      - name: Push release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-bundle/*.zip
            win32-bundle/*.zip